include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore  # 🔥 Ignore bogus JsonKey warnings

linter:
  rules:
    always_specify_types: true
    avoid_dynamic_calls: true
    avoid_types_on_closure_parameters: false
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    unnecessary_late: true
    unnecessary_nullable_for_final_variable_declarations: true
