// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGvRqxrtcAUuiyoarFnAziP7Mw93O9Og',
    appId: '1:34506647750:android:231995162200bb37d14fc7',
    messagingSenderId: '34506647750',
    projectId: 'tfa-auth-demo-2025',
    storageBucket: 'tfa-auth-demo-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyIoqUWHs4Scm6NQPF76Sv_1pp0e6uWI',
    appId: '1:34506647750:ios:1db0ccc3abc5a9e1d14fc7',
    messagingSenderId: '34506647750',
    projectId: 'tfa-auth-demo-2025',
    storageBucket: 'tfa-auth-demo-2025.firebasestorage.app',
    iosBundleId: 'com.example.tfa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnWPSW2jpuv5aWWGWleiud7irN9vApJs',
    appId: '1:34506647750:web:f09b7e134fd617b2d14fc7',
    messagingSenderId: '34506647750',
    projectId: 'tfa-auth-demo-2025',
    authDomain: 'tfa-auth-demo-2025.firebaseapp.com',
    storageBucket: 'tfa-auth-demo-2025.firebasestorage.app',
  );

}